{{ config(
    materialized = "table",
    tags = ["dim"]
) }}

WITH remove_spaces AS (

    SELECT
        DISTINCT especificacao_papel AS cod_especificacao_papel
    FROM
        {{ ref("stg_b3_raw_zone") }}
)
SELECT
    remove_spaces.cod_especificacao_papel,
    CASE
        WHEN remove_spaces.cod_especificacao_papel = 'BDR' THEN 'BDR'
        WHEN remove_spaces.cod_especificacao_papel = 'BNS' THEN 'BONUS DE Subscricao EM ACOES MISCELANEA'
        WHEN remove_spaces.cod_especificacao_papel = 'BNSBA' THEN 'BONUS DE Subscricao EM ACOES PREFERENCIA'
        WHEN remove_spaces.cod_especificacao_papel = 'BNSORD' THEN 'BONUS DE Subscricao EM ACOES ORDINARIAS'
        WHEN remove_spaces.cod_especificacao_papel = 'BNSPA' THEN 'BONUS DE Subscricao EM ACOES PREFERENCIA'
        WHEN remove_spaces.cod_especificacao_papel = 'BNSPB' THEN 'BONUS DE Subscricao EM ACOES PREFERENCIA'
        WHEN remove_spaces.cod_especificacao_papel = 'BNSPC' THEN 'BONUS DE Subscricao EM ACOES PREFERENCIA'
        WHEN remove_spaces.cod_especificacao_papel = 'BNSPD' THEN 'BONUS DE Subscricao EM ACOES PREFERENCIA'
        WHEN remove_spaces.cod_especificacao_papel = 'BNSPE' THEN 'BONUS DE Subscricao EM ACOES PREFERENCIA'
        WHEN remove_spaces.cod_especificacao_papel = 'BNSPF' THEN 'BONUS DE Subscricao EM ACOES PREFERENCIA'
        WHEN remove_spaces.cod_especificacao_papel = 'BNSPG' THEN 'BONUS DE Subscricao EM ACOES PREFERENCIA'
        WHEN remove_spaces.cod_especificacao_papel = 'BNSPH' THEN 'BONUS DE Subscricao EM ACOES PREFERENCIA'
        WHEN remove_spaces.cod_especificacao_papel = 'BNSPRE' THEN 'BONUS DE Subscricao EM ACOES PREFERENCIA'
        WHEN remove_spaces.cod_especificacao_papel = 'CDA' THEN 'CERTIFICADO DE DEPOSITO DE ACOES ORDINARIAS'
        WHEN remove_spaces.cod_especificacao_papel = 'CI' THEN 'FUNDO DE INVESTIMENTO'
        WHEN remove_spaces.cod_especificacao_papel = 'CIATZ' THEN 'Fundo de Investimento Atualizacao'
        WHEN remove_spaces.cod_especificacao_papel = 'CIEA' THEN 'Fundo de Investimento Ex-Atualizacao'
        WHEN remove_spaces.cod_especificacao_papel = 'CIEBA' THEN 'Fundo de Investimento Ex-Bonificacao e Ex-Atualizacao'
        WHEN remove_spaces.cod_especificacao_papel = 'CIED' THEN 'Fundo de Investimento Ex-dividendo'
        WHEN remove_spaces.cod_especificacao_papel = 'CIER' THEN 'Fundo de Investimento Ex-Rendimento'
        WHEN remove_spaces.cod_especificacao_papel = 'CIERA' THEN 'Fundo de Investimento Ex-rendimento e Ex-Atualizacao'
        WHEN remove_spaces.cod_especificacao_papel = 'CIERB' THEN 'Fundo de Investimento Ex-rendimento e Ex-Bonificacao'
        WHEN remove_spaces.cod_especificacao_papel = 'CIERS' THEN 'Fundo de Investimento Ex-Rendimento e Ex-Subscricao'
        WHEN remove_spaces.cod_especificacao_papel = 'CIES' THEN 'Fundo de Investimento Ex-Subscricao'
        WHEN remove_spaces.cod_especificacao_papel = 'CPA' THEN 'CERTIF. DE POTENCIAL ADIC. DE CONSTRUCAO'
        WHEN remove_spaces.cod_especificacao_papel = 'DIR' THEN 'DIREITOS DE Subscricao MISCELANEA (BONUS)'
        WHEN remove_spaces.cod_especificacao_papel = 'DIRDEB' THEN 'Direito de Debênture'
        WHEN remove_spaces.cod_especificacao_papel = 'DIRORD' THEN 'DIREITOS DE Subscricao EM ACOES ORDINARIAS'
        WHEN remove_spaces.cod_especificacao_papel = 'DIRPA' THEN 'DIREITOS DE Subscricao EM ACOES PREFERENCIAIS'
        WHEN remove_spaces.cod_especificacao_papel = 'DIRPB' THEN 'DIREITOS DE Subscricao EM ACOES PREFERENCIAIS'
        WHEN remove_spaces.cod_especificacao_papel = 'DIRPC' THEN 'DIREITOS DE Subscricao EM ACOES PREFERENCIAIS'
        WHEN remove_spaces.cod_especificacao_papel = 'DIRPD' THEN 'DIREITOS DE Subscricao EM ACOES PREFERENCIAIS'
        WHEN remove_spaces.cod_especificacao_papel = 'DIRPE' THEN 'DIREITOS DE Subscricao EM ACOES PREFERENCIAIS'
        WHEN remove_spaces.cod_especificacao_papel = 'DIRPF' THEN 'DIREITOS DE Subscricao EM ACOES PREFERENCIAIS'
        WHEN remove_spaces.cod_especificacao_papel = 'DIRPG' THEN 'DIREITOS DE Subscricao EM ACOES PREFERENCIAIS'
        WHEN remove_spaces.cod_especificacao_papel = 'DIRPH' THEN 'DIREITOS DE Subscricao EM ACOES PREFERENCIAIS'
        WHEN remove_spaces.cod_especificacao_papel = 'DIRPR' THEN 'DIREITOS DE Subscricao EM ACOES RESGATAVEIS'
        WHEN remove_spaces.cod_especificacao_papel = 'DIRPRA' THEN 'DIREITOS DE Subscricao EM ACOES RESGATAVEIS'
        WHEN remove_spaces.cod_especificacao_papel = 'DIRPRB' THEN 'DIREITOS DE Subscricao EM ACOES RESGATAVEIS'
        WHEN remove_spaces.cod_especificacao_papel = 'DIRPRC' THEN 'DIREITOS DE Subscricao EM ACOES RESGATAVEIS'
        WHEN remove_spaces.cod_especificacao_papel = 'DIRPRE' THEN 'DIREITOS DE Subscricao EM ACOES PREFERENCIAIS'
        WHEN remove_spaces.cod_especificacao_papel = 'FIDC' THEN 'Fundo de Investimento em Direitos Creditorios'
        WHEN remove_spaces.cod_especificacao_papel = 'M1REC' THEN 'RECIBO DE Subscricao DE MISCELANEAS'
        WHEN remove_spaces.cod_especificacao_papel = 'ON' THEN 'ACOES ORDINARIAS NOMINATIVAS'
        WHEN remove_spaces.cod_especificacao_papel = 'ONATZ' THEN 'Acoes ORDINARIAS Atualizacao'
        WHEN remove_spaces.cod_especificacao_papel = 'ONEB' THEN 'Acoes ORDINARIAS Ex-Bonificacao'
        WHEN remove_spaces.cod_especificacao_papel = 'ONED' THEN 'Acoes ORDINARIAS Ex-Dividendo'
        WHEN remove_spaces.cod_especificacao_papel = 'ONEDB' THEN 'Acoes ORDINARIAS Ex-Dividendo e Ex-Bonificacao'
        WHEN remove_spaces.cod_especificacao_papel = 'ONEDJ' THEN 'Acoes ORDINARIAS Ex-dividendo e Ex-Juros'
        WHEN remove_spaces.cod_especificacao_papel = 'ONEDR' THEN 'Acoes ORDINARIAS Ex-Dividendo e Ex-Rendimento'
        WHEN remove_spaces.cod_especificacao_papel = 'ONEG' THEN 'Acoes ORDINARIAS Ex-Grupamento'
        WHEN remove_spaces.cod_especificacao_papel = 'ONEJ' THEN 'Acoes ORDINARIAS Ex-juros'
        WHEN remove_spaces.cod_especificacao_papel = 'ONEJB' THEN 'Acoes ORDINARIAS Ex-juros e Ex-Bonificacao'
        WHEN remove_spaces.cod_especificacao_papel = 'ONEJS' THEN 'Acoes ORDINARIAS Ex-Juros e Ex-Subscricao'
        WHEN remove_spaces.cod_especificacao_papel = 'ONER' THEN 'Acoes ORDINARIAS Ex-Rendimento'
        WHEN remove_spaces.cod_especificacao_papel = 'ONERJ' THEN 'Acoes ORDINARIAS Ex-Rendimento e Ex-Juros'
        WHEN remove_spaces.cod_especificacao_papel = 'ONES' THEN 'Acoes ORDINARIAS Ex-Subscricao'
        WHEN remove_spaces.cod_especificacao_papel = 'ONP' THEN 'ACOES ORDINARIAS NOMINATIVAS COM DIREITO'
        WHEN remove_spaces.cod_especificacao_papel = 'ONREC' THEN 'RECIBO DE Subscricao EM ACOES ORDINARIAS'
        WHEN remove_spaces.cod_especificacao_papel = 'OR' THEN 'ACOES ORDINARIAS NOMINATIVAS RESGATAVEIS'
        WHEN remove_spaces.cod_especificacao_papel = 'ORP' THEN 'ACOES ORDINARIAS NOMINATIVAS RESGATAVEIS'
        WHEN remove_spaces.cod_especificacao_papel = 'PCD' THEN 'POSICAO CONSOLIDADA DA DIVIDA'
        WHEN remove_spaces.cod_especificacao_papel = 'PN' THEN 'ACOES PREFERENCIAIS NOMINATIVAS'
        WHEN remove_spaces.cod_especificacao_papel = 'PNEB' THEN 'Acoes Preferenciais Ex-Bonificacao'
        WHEN remove_spaces.cod_especificacao_papel = 'PNED' THEN 'Acoes Preferenciais Ex-Dividendo'
        WHEN remove_spaces.cod_especificacao_papel = 'PNEDB' THEN 'Acoes Preferenciais Ex-Dividendo e Ex-Bonificacao'
        WHEN remove_spaces.cod_especificacao_papel = 'PNEDJ' THEN 'Acoes Preferenciais Ex-dividendo e Ex-Juros'
        WHEN remove_spaces.cod_especificacao_papel = 'PNEDR' THEN 'Acoes Preferenciais Ex-Dividendo e Ex-Rendimento'
        WHEN remove_spaces.cod_especificacao_papel = 'PNEJ' THEN 'Acoes Preferenciais Ex-Juros'
        WHEN remove_spaces.cod_especificacao_papel = 'PNEJB' THEN 'Acoes Preferenciais Ex-juros e Ex-Bonificacao'
        WHEN remove_spaces.cod_especificacao_papel = 'PNEJS' THEN 'Acoes Preferenciais Ex-Juros e Ex-Subscricao'
        WHEN remove_spaces.cod_especificacao_papel = 'PNES' THEN 'Acoes Preferenciais Ex-Subscricao'
        WHEN remove_spaces.cod_especificacao_papel = 'PNP' THEN 'ACOES PREFERENCIAIS NOMINATIVAS COM DIREITO'
        WHEN remove_spaces.cod_especificacao_papel = 'PNREC' THEN 'RECIBO DE Subscricao EM ACOES PREFERENCIAIS'
        WHEN remove_spaces.cod_especificacao_papel = 'PNA' THEN 'ACOES PREFERENCIAIS NOMINATIVAS CLASSE A'
        WHEN remove_spaces.cod_especificacao_papel = 'PNAEB' THEN 'Acoes Preferenciais Classe A Ex-BonificacaoPreferencial'
        WHEN remove_spaces.cod_especificacao_papel = 'PNAEDR' THEN 'Acoes Preferenciais Classe A Ex-Dividendo e Ex-Rendimento'
        WHEN remove_spaces.cod_especificacao_papel = 'PNAEJ' THEN 'Acoes Preferenciais Classe A Ex-Juros'
        WHEN remove_spaces.cod_especificacao_papel = 'PNAS' THEN 'Acoes Preferenciais Classe A Preferencial Ex-Subscricao'
        WHEN remove_spaces.cod_especificacao_papel = 'PNAP' THEN 'ACOES PREFERENCIAIS NOMINATIVAS CLASSE A'
        WHEN remove_spaces.cod_especificacao_papel = 'PNAREC' THEN 'RECIBO DE Subscricao EM ACOES PREFERENCIAIS'
        WHEN remove_spaces.cod_especificacao_papel = 'PNB' THEN 'ACOES PREFERENCIAIS NOMINATIVAS CLASSE B'
        WHEN remove_spaces.cod_especificacao_papel = 'PNBEB' THEN 'Acoes Preferenciais Classe B Ex-Bonificacao'
        WHEN remove_spaces.cod_especificacao_papel = 'PNBED' THEN 'Acoes Preferenciais Classe B Ex-Dividendo'
        WHEN remove_spaces.cod_especificacao_papel = 'PNBEDR' THEN 'Acoes Preferenciais Classe B Ex-Dividendo e Ex-Rendimento'
        WHEN remove_spaces.cod_especificacao_papel = 'PNBEJ' THEN 'Acoes Preferenciais Classe B Ex-Juros'
        WHEN remove_spaces.cod_especificacao_papel = 'PNBP' THEN 'ACOES PREFERENCIAIS NOMINATIVAS CLASSE B'
        WHEN remove_spaces.cod_especificacao_papel = 'PNBREC' THEN 'RECIBO DE Subscricao EM ACOES PREFERENCIAIS'
        WHEN remove_spaces.cod_especificacao_papel = 'PNC' THEN 'ACOES PREFERENCIAIS NOMINATIVAS CLASSE C'
        WHEN remove_spaces.cod_especificacao_papel = 'PNCED' THEN 'Acoes Preferenciais Classe C Preferencial Classe C Ex-Dividendo'
        WHEN remove_spaces.cod_especificacao_papel = 'PNCP' THEN 'ACOES PREFERENCIAIS NOMINATIVAS CLASSE C'
        WHEN remove_spaces.cod_especificacao_papel = 'PNCREC' THEN 'RECIBO DE Subscricao EM ACOES PREFERENCIAIS'
        WHEN remove_spaces.cod_especificacao_papel = 'PND' THEN 'ACOES PREFERENCIAIS NOMINATIVAS CLASSE D'
        WHEN remove_spaces.cod_especificacao_papel = 'PNDED' THEN 'Acoes Preferenciais Classe D Ex-Dividendo'
        WHEN remove_spaces.cod_especificacao_papel = 'PNDP' THEN 'ACOES PREFERENCIAIS NOMINATIVAS CLASSE D'
        WHEN remove_spaces.cod_especificacao_papel = 'PNDREC' THEN 'RECIBO DE Subscricao EM ACOES PREFERENCIAIS'
        WHEN remove_spaces.cod_especificacao_papel = 'PNE' THEN 'ACOES PREFERENCIAIS NOMINATIVAS CLASSE E'
        WHEN remove_spaces.cod_especificacao_papel = 'PNEED' THEN 'Acoes Preferenciais Classe E Ex-Dividendo'
        WHEN remove_spaces.cod_especificacao_papel = 'PNEP' THEN 'ACOES PREFERENCIAIS NOMINATIVAS CLASSE E'
        WHEN remove_spaces.cod_especificacao_papel = 'PNEREC' THEN 'RECIBO DE Subscricao EM ACOES PREFERENCIAIS'
        ELSE NULL
    END AS desc_especificacao_papel
FROM
    remove_spaces
