dbt_b3:
  target: prd
  outputs:
    prd:
      dataset: dataset-name
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: creds.json
      location: US
      method: service-account
      priority: interactive
      project: project-name
      threads: 1
      type: bigquery
